trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'package'
    options: '-DskipTests'
  displayName: 'Build WAR File'

- task: PublishTestResults@2
  inputs:
    testResultsFiles: '$(Build.ArtifactStagingDirectory)/results.xml'
    testRunTitle: 'Postman Tests'
  condition: succeededOrFailed()  # Ensure results are published even if tests fail

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'  # Adjust if necessary
    ArtifactName: 'drop'
    publishLocation: 'Container'
