trigger:
- main  # Adjust this to your branch if necessary

pool:
  vmImage: 'ubuntu-latest'  # Change to 'windows-latest' if needed

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g newman
  displayName: 'Install Newman'

- script: |
    echo "Listing files in $(Build.SourcesDirectory)"
    ls -R $(Build.SourcesDirectory)
  displayName: 'Verify .war file in source directory'

# Ensure the directory for the .war file exists
- script: |
    mkdir -p $(Build.ArtifactStagingDirectory)/war-directory
  displayName: 'Create target directory for .war file'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'  # Adjust the path to where your .war file is located
    Contents: '**/*.war'  # Matches all .war files
    TargetFolder: '$(Build.ArtifactStagingDirectory)/war-directory'  # Define your target directory
  displayName: 'Copy .war file to directory'

# Verify that the .war file has been copied to the staging directory
- script: |
    echo "Listing files in $(Build.ArtifactStagingDirectory)/war-directory"
    ls -R $(Build.ArtifactStagingDirectory)/war-directory
  displayName: 'Verify .war file in target directory'

- task: PublishTestResults@2
  inputs:
    testResultsFiles: '$(Build.ArtifactStagingDirectory)/results.xml'
    testRunTitle: 'Postman Tests'
  condition: succeededOrFailed()

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)/war-directory'  # The directory where the .war file is stored
    artifactName: 'WARFile'
  displayName: 'Publish .war file as Artifact'

