trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseNode@1
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js 16'

- script: |
    npm install -g newman
  displayName: 'Install Newman'

- script: |
    bash run-tests.sh
  displayName: 'Run Postman Tests'
