trigger:
- main  # Adjust this to your branch if necessary

pool:
  vmImage: 'ubuntu-latest'  # You can change this to 'windows-latest' or another agent pool if needed

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'  # Update to Node.js version 16 or higher
  displayName: 'Install Node.js'

- script: |
    npm install -g newman
  displayName: 'Install Newman'
- script: |
    ls -R $(Build.SourcesDirectory)
  displayName: 'List files in source directory'

- script: |
    newman run $(Build.SourcesDirectory)/path/to/your/PostmanCollection.json --reporters cli,junit --reporter-junit-export $(Build.ArtifactStagingDirectory)/results.xml
  displayName: 'Run Postman Collection'

- task: PublishTestResults@2
  inputs:
    testResultsFiles: '$(Build.ArtifactStagingDirectory)/results.xml'
    testRunTitle: 'Postman Tests'
  condition: succeededOrFailed()  # Ensure results are published even if tests fail